#!/usr/bin/env bash
DEFAULT="\e[0m";
BOLD="\e[1m";
UNBOLD="\e[22m";
NOTBOLD="\e[22m";
RED="\e[31m";
GREEN="\e[32m";
YELLOW="\e[33m";
BLUE="\e[34m";
PINK="\e[35m";
CYAN="\e[36m";

function isInteractiveShell()
{
  if [[ $- =~ i ]]
  then
      return 0
  else
    return -1
  fi
  
}
export -f isInteractiveShell

function logPrint()
{
    if isInteractiveShell 
    then
        echo -e $*$DEFAULT;
    fi
}
export -f logPrint

function isSuse()
{
    grep -qi suse /etc/os-release
}

function isBsd()
{
  uname -a | egrep -iq bsd 
}

logPrint "${GREEN}Reading bashrc.init$DEFAULT"

